#!/bin/sh
set -eu
SRCDIR=/freebsd-builder/freebsd-src
OBJDIR=/freebsd-builder/build
TARER=/freebsd-builder/fbsd-lab-infra/buildhost/bin/mk-freebsd-tar
SRC_CONF=~/repos/fbsd-bbb/src.conf
#MAKE="MAKEOBJDIRPREFIX=$OBJDIR make -j16 -C $SRCDIR buildworld TARGET=arm64 TARGET_ARCH=aarch64"
#MAKE="MAKEOBJDIRPREFIX=$OBJDIR make -j1 -C $SRCDIR buildworld NO_CLEAN=yes TARGET=arm64 TARGET_ARCH=aarch64"
#MAKE="MAKEOBJDIRPREFIX=$OBJDIR make -j32 buildkernel KERNCONF=GENERIC-MMCCAM TARGET=arm64 TARGET_ARCH=aarch64"
#MAKE="MAKEOBJDIRPREFIX=$OBJDIR make -j32 buildworld TARGET=arm64 TARGET_ARCH=aarch64"
#MAKE="MAKEOBJDIRPREFIX=$OBJDIR make -j32 buildworld buildkernel KERNCONF=GENERIC-MMCCAM TARGET=arm64 TARGET_ARCH=aarch64"
MAKE="MAKEOBJDIRPREFIX=$OBJDIR make -j32 buildworld buildkernel NO_CLEAN=yes KERNCONF=GENERIC-MMCCAM TARGET=amd64 TARGET_ARCH=amd64"
#MAKE="MAKEOBJDIRPREFIX=$OBJDIR make -j16 SRCCONF=/tmp/src.conf -C $SRCDIR buildworld"
#MAKE="MAKEOBJDIRPREFIX=$OBJDIR make -j16 -C $SRCDIR buildkernel KERNCONF=GENERIC-MMCCAM NO_CLEAN=yes TARGET=arm64 TARGET_ARCH=aarch64"
#MAKE="MAKEOBJDIRPREFIX=$OBJDIR make-C $SRCDIR buildworld buildkernel NO_CLEAN=yes KERNCONF=GENERIC-MMCCAM"

ISH_ARGS='-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_github'

VM="fbsd-builder.bakulin.de"

#REMOTECMD=`eval "echo ${REMOTECMD}"`
REMOTECMD="${REMOTECMD}"
LOGSUFFIX=$(date "+%Y-%m-%d_%H:%M")
LOGFILE="/tmp/build_${LOGSUFFIX}"
#scp $ISH_ARGS $SRC_CONF $vmip:/tmp/src.conf
echo "************************************************************"
echo "VM:  $VM"
echo "CMD: $REMOTECMD"
echo "Log: $LOGFILE"
echo "************************************************************"

./builder-is-running || (
    echo === Starting VM
    ./builder-start
    echo === Waiting for $VM to be reachable over SSH
    ./builder-wait
)

# Setup remote host -- copy files, create dirs, update build scripts from git
ssh $ISH_ARGS -A $VM "cd /freebsd-builder/fbsd-lab-infra && git pull && sudo mkdir -pm0777 $OBJDIR"
#time ssh $ISH_ARGS $VM "cd $SRCDIR && time $MAKE > $LOGFILE; tail -n4 $LOGFILE"
time ssh $ISH_ARGS $VM "$REMOTECMD"
#ssh $ISH_ARGS $vmip "cd $SRCDIR && git rev-parse --verify HEAD"

#./builder-stop
